package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import control.Sessione;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FormStudente {
    private JLabel titoloStudente;
    private JButton effettuaPrenotazioneButton;
    private JButton annullaPrenotazioneButton;
    private JButton effettuaCheckInButton;
    private JButton fasceOrarieDisponibiliButton;
    private JButton profiloPersonaleButton;
    private JPanel panelStudente;

    // Scritte da me
    private JFrame frame;
    private Sessione session;

    /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
    private void $$$setupUI$$$() {
        panelStudente = new JPanel();
        panelStudente.setLayout(new GridLayoutManager(8, 2, new Insets(0, 100, 0, 100), -1, -1));
        titoloStudente = new JLabel();
        titoloStudente.setText("Studente");
        panelStudente.add(titoloStudente, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        effettuaPrenotazioneButton = new JButton();
        effettuaPrenotazioneButton.setText("Effettua prenotazionea");
        panelStudente.add(effettuaPrenotazioneButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        annullaPrenotazioneButton = new JButton();
        annullaPrenotazioneButton.setText("Annulla prenotazione");
        panelStudente.add(annullaPrenotazioneButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        effettuaCheckInButton = new JButton();
        effettuaCheckInButton.setText("Effettua Check-In");
        panelStudente.add(effettuaCheckInButton, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fasceOrarieDisponibiliButton = new JButton();
        fasceOrarieDisponibiliButton.setText("Visualizza fasce orarie");
        panelStudente.add(fasceOrarieDisponibiliButton, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        profiloPersonaleButton = new JButton();
        profiloPersonaleButton.setText("Profilo personale");
        panelStudente.add(profiloPersonaleButton, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelStudente.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(10, 10), null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panelStudente.add(spacer2, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(10, 10), null, null, 0, false));
    }

        /**
         * @noinspection ALL
         */
        public JComponent $$$getRootComponent$$$() {
        return panelStudente;
    }

    public FormStudente(Sessione session) {
        this.frame = new JFrame("Studente");


        fasceOrarieDisponibiliButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FormConsultaFasceOrarie formConsultaFasceOrarie =  new FormConsultaFasceOrarie(session);
                formConsultaFasceOrarie.setVisible(true);
                frame.dispose();
            }
        });

        effettuaPrenotazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FormEffettuaPrenotazione formEffettuaPrenotazione = new FormEffettuaPrenotazione(session);
                formEffettuaPrenotazione.setVisible(true);
                frame.dispose();
            }
        });
    }
}
