package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class FormConsultaFasceOrarie {
    private JLabel Titolo;
    private JTable table1;
    private JPanel panelConsultaFasceOrarie;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelConsultaFasceOrarie = new JPanel();
        panelConsultaFasceOrarie.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        Titolo = new JLabel();
        Titolo.setText("Consulta Fasce Orarie");
        panelConsultaFasceOrarie.add(Titolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        table1 = new JTable();
        table1.setBackground(new Color(-12537895));
        panelConsultaFasceOrarie.add(table1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelConsultaFasceOrarie;
    }

    public JPanel getContentPanel() {
        return panelConsultaFasceOrarie;
    }

    public static void consultaFasceOrarieRender(JFrame frame) {

        frame.setContentPane(new FormConsultaFasceOrarie().panelConsultaFasceOrarie);
        frame.revalidate();
        frame.repaint();
    }


}
